#!/bin/bash

source xsmaug.conf

if [ ! -f "$xsmaug" ]; then
	echo
	echo "ERROR! No XSMAUG executable found!";
	echo "Try building the source first with 'make'.";
	echo
	exit 1;
fi;

echo
echo "          - (( $xsmaug $version )) -" 
echo 
echo "                \"$realm\""
echo

sleep 2;

cd $realm

../$xsmaug $port > $log

